use_frameworks!

platform :ios, '9.0'

target 'YDDPPStickerKeyboard_Example' do
  pod 'YDDPPStickerKeyboard', :path => '../'

  target 'YDDPPStickerKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
